#!/usr/bin/env python3

import sys
import os
import subprocess

args = sys.argv[1:]

new_args = ["xcrun"]

# Pick up SDK from environment if not passed
if "SDK_NAME" in os.environ:
    has_sdk = False
    for i in range(len(args)):
        if args[i] == "--sdk":
            has_sdk = True
            break
    
    if not has_sdk:
        new_args.extend(["--sdk", os.environ["SDK_NAME"]])

# Pick up tool from environment if not passed
if "IOSXCRUN_TOOL" in os.environ:
    has_tool = False
    tools = ["clang", "clang++", "ld", "ar", "libtool", "ranlib", "strip", "install_name_tool", "dsymutil"]
    for i in range(len(args)):
        if args[i] in tools:
            has_tool = True
            break
    
    if not has_tool:
        new_args.append(os.environ["IOSXCRUN_TOOL"])

is_just_c_not_cpp = True
for arg in args:
    if arg.endswith(".cpp") or arg.endswith(".cxx") or arg.endswith(".cc"):
        is_just_c_not_cpp = False

# Fallback to clang/clang++ if no tool is specified and we have files to compile
has_tool = False
tools = ["clang", "clang++", "ld", "ar", "libtool", "ranlib", "strip", "install_name_tool", "dsymutil"]
for i in range(len(new_args)):
    if new_args[i] in tools:
        has_tool = True
        break

if not has_tool:
    for arg in args:
        if arg.startswith("-"):
            continue
        if arg.endswith(".c") or arg.endswith(".cpp") or arg.endswith(".cxx") or arg.endswith(".cc") or arg.endswith(".m") or arg.endswith(".mm") or arg.endswith(".o") or arg.endswith(".a") or arg.endswith(".dylib") or arg.endswith(".so"):
            if is_just_c_not_cpp:
                new_args.append("clang")
            else:
                new_args.append("clang++")
            has_tool = True
            break

assembly = False
is_preprocessor = False
for arg in args:

    if ("--version" in args or "-Wl,--version" in args) and arg.startswith("-Wl,--defsym"):
        continue

    if arg == "-static":
        continue

    if arg.startswith("--host="):
        continue

    if arg == "--target=ios-cross":
        continue

    # prioritize -target over -arch
    if new_args[-1] == "-arch" and "-target" in args:
        new_args.pop(-1)
        continue
    
    if new_args[-1] == "--sdk" and arg == "darwin":
        arg = "macosx"

    if arg == "-E" and len(new_args) == 1:
        # Invoked as preprocessor without a specified compiler
        new_args.append("clang")

    if arg == "-E" and new_args[-1] == "clang":
        is_preprocessor = True

    if arg == "-L/usr/local/lib":
        continue
    
    if arg == "-nologo":
        continue

    if arg == "-lgfortran":
        continue

    # I don't know why but something is forcing to link to a "Python" framework even if we already specified another Python framework name
    if arg == "Python" and new_args[-1] == "-framework":
        if "PYTHON_LINK" in os.environ and not arg in os.environ["PYTHON_LINK"].split(" "):
            new_args.pop(-1)
            continue

    # astropy fails with unused linker flags
    if arg == "-Wall" and new_args[-1] == "-Werror":
        new_args.pop(-1)
        continue

    # gensim passes xcrun flags to the compiler?
    if new_args[-1] == "--sdk" and ("clang" in new_args or "clang++" in new_args):
        new_args.pop(-1)
        continue
    elif (arg == "clang" or arg == "clang++") and ("clang" in new_args or "clang++" in new_args):
        continue

    if arg == "-lclang_rt.osx" and "SDK_NAME" in os.environ:
        sdk_name = os.environ["SDK_NAME"]
        if sdk_name == "iphoneos":
             arg = "-lclang_rt.ios"
        elif sdk_name == "iphonesimulator":
            arg = "-lclang_rt.iossim"
        elif sdk_name == "watchos":
            arg = "-lclang_rt.watchos"
        elif sdk_name == "watchsimulator":
            arg = "-lclang_rt.watchossim"
        elif sdk_name == "appletvos":
            arg = "-lclang_rt.tvos"
        elif sdk_name == "appletvsimulator":
            arg = "-lclang_rt.tvossim"
        else:
            arg = "-lclang_rt.osx"

    if arg.endswith(".S") and new_args[-1] == "-c":
        assembly = True

    if arg == "-march=native":
        continue
    elif (arg == "-arch" or arg == "arm64" or arg == "x86_64" or arg == "armv7k" or arg == "arm64_32") and (new_args[-1] == "-isysroot" or is_preprocessor):
        continue
    else:
        if arg == "-bundle":
            arg = "-shared"
        elif arg == "fPIC":
            arg = "-fPIC"
    new_args.append(arg)

if len(new_args) > 1 and new_args[1].startswith("-") and new_args[1] != "--sdk" and "clang" not in new_args and assembly:
    new_args.insert(1, "clang")

p = subprocess.Popen(new_args)
p.wait()
sys.exit(p.returncode)
